### ISSUE TITLE
Incompatible with Better Combat mod

### ISSUE THREAD

**Issue by brooswit** [GekidoLukas/weaponleveling#17]
Using just the latest version of weaponleveling and the latest version of better combat, I get a `Mixin apply failed weaponleveling.mixin.json:MixinPlayer` error.

Here is an export of a modpack that just includes these two mods.

[weapon-leveling-test.zip](https://github.com/GeradesoLukas/weaponleveling/files/9731865/weapon-leveling-test.zip)

When starting this modpack, the game never starts, and latest.log contains the following:

```
[00:58:02] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[00:58:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/broos/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[00:58:02] [main/INFO]: Found mod file bettercombat-forge-1.4.4+1.18.2.jar of type MOD with locator {mods folder locator at C:\Users\broos\curseforge\minecraft\Instances\weapon-leveling-test\mods}
[00:58:02] [main/INFO]: Found mod file cloth-config-6.4.90-forge.jar of type MOD with locator {mods folder locator at C:\Users\broos\curseforge\minecraft\Instances\weapon-leveling-test\mods}
[00:58:02] [main/INFO]: Found mod file player-animation-lib-forge-0.3.5.jar of type MOD with locator {mods folder locator at C:\Users\broos\curseforge\minecraft\Instances\weapon-leveling-test\mods}
[00:58:02] [main/INFO]: Found mod file weaponleveling-1.18.2-1.3.4.jar of type MOD with locator {mods folder locator at C:\Users\broos\curseforge\minecraft\Instances\weapon-leveling-test\mods}
[00:58:02] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[00:58:02] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[00:58:02] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[00:58:02] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[00:58:02] [main/INFO]: Found mod file forge-1.18.2-40.1.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[00:58:03] [main/INFO]: Compatibility level set to JAVA_17
[00:58:03] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.1.0, --gameDir, C:\Users\broos\curseforge\minecraft\Instances\weapon-leveling-test, --assetsDir, C:\Users\broos\curseforge\minecraft\Install\assets, --uuid, 6e18f064b8b6401d8dd48943091a825e, --username, brooswit, --assetIndex, 1.18, --accessToken, ????????, --clientId, NWExNjM3NDktZWRkMS00NmI2LWFiNTgtMjRkYWNiY2VlNTQ0, --xuid, 2535472301325597, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[00:58:04] [main/WARN]: Error loading class: se/mickelus/tetra/items/modular/impl/bow/ModularBowItem (java.lang.ClassNotFoundException: se.mickelus.tetra.items.modular.impl.bow.ModularBowItem)
[00:58:04] [main/WARN]: Error loading class: se/mickelus/tetra/items/modular/impl/crossbow/ModularCrossbowItem (java.lang.ClassNotFoundException: se.mickelus.tetra.items.modular.impl.crossbow.ModularCrossbowItem)
[00:58:04] [pool-3-thread-1/FATAL]: Mixin apply failed weaponleveling.mixin.json:MixinPlayer -> net.minecraft.world.entity.player.Player: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 1 for @ModifyArg is invalid for args (Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/item/ItemStack;), expected Lnet/minecraft/world/item/ItemStack; on net/minecraft/world/entity/player/Player::replaceEmpty [INJECT Applicator Phase -> weaponleveling.mixin.json:MixinPlayer -> Apply Injections ->  -> Inject -> weaponleveling.mixin.json:MixinPlayer->@ModifyArg::replaceEmpty(Lnet/minecraft/world/item/ItemStack;)Lnet/minecraft/world/item/ItemStack;]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 1 for @ModifyArg is invalid for args (Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/item/ItemStack;), expected Lnet/minecraft/world/item/ItemStack; on net/minecraft/world/entity/player/Player::replaceEmpty [INJECT Applicator Phase -> weaponleveling.mixin.json:MixinPlayer -> Apply Injections ->  -> Inject -> weaponleveling.mixin.json:MixinPlayer->@ModifyArg::replaceEmpty(Lnet/minecraft/world/item/ItemStack;)Lnet/minecraft/world/item/ItemStack;]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:123) ~[forge-1.18.2-40.1.0-universal.jar%2360!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:108) ~[forge-1.18.2-40.1.0-universal.jar%2360!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:391) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:170) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by GekidoLukas** [comment]
Hey, I forgot to add this, but it seems like you need a newer forge version. I myself use 40.1.70 and higher, and it works without any issues there. I will add this as a requirement in the next update.

**Comment by thedaymare16** [comment]
> Hey, I forgot to add this, but it seems like you need a newer forge version. I myself use 40.1.70 and higher, and it works without any issues there. I will add this as a requirement in the next update.

It happened to me today since adding the mod, I use the lastest 1.18.2 forge version which is 40.1.80 and still it crashes my server, will leave the log here
[latest.log](https://github.com/GeradesoLukas/weaponleveling/files/9742633/latest.log)

**Comment by CCCClear** [comment]
I don't think there is a conflict between these two mods because I can run both mods normally.

**Comment by thedaymare16** [comment]
> 

I will try with only Better Combat and this mod just to be sure on my end, if it works then it may be another mod :(

**Comment by thedaymare16** [comment]
It works with only Better Combat, my bad, now I need to find what mod is causing it to crash, hmm

**Comment by brooswit** [comment]
Just tested on the latest forge version and I can confirm it works. Thanks!
