### ISSUE TITLE
Getting "Modules weaponleveling and MixinExtras.beta._9" error

### ISSUE THREAD

**Issue by s3tupw1zard** [GekidoLukas/weaponleveling#42]
**Describe the bug**
The Game crashes.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3

**To Reproduce**
1. Install all the mods I've added to my pack.
2. Click on play

**Expected behavior**
The Forge Modpack should start normally.

**Additional context**
This is my List of Mods:

```
  [✔] [1.18.2-forge]-Epic-Knights-8.2
  [✔] AdvancementPlaques-1.18.2-1.4.5.1
  [✔] AI-Improvements-1.18.2-0.5.2
  [✔] allthemodium-1.9.6-1.18.2-40.1.51
  [✔] AmbientSounds_FORGE_v5.0.16_mc1.18.2
  [✔] antiqueatlas-7.1.1-forge-mc1.18.2
  [✔] appleskin-forge-mc1.18.2-2.4.1
  [✔] architectury-4.11.93-forge
  [✔] art_of_forging-1.5.5-1.18.2
  [✔] auto_third_person-forge-1.18.2-2
  [✔] AutoRegLib-1.7-53
  [✔] badpackets-forge-0.1.3
  [✔] balm-3.2.6
  [✔] BetterAnimationsCollection-v3.0.0-1.18.2-Forge
  [✔] bettercombat-forge-1.6.2+1.18.2
  [✔] BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2
  [✔] BetterF3-3.0.0-Forge-1.18.2
  [✔] betterstats-2.2.2+1.18.2
  [✔] BetterThirdPerson-Forge-1.18.2-1.9.0
  [✔] betterwithminecolonies-1.16.5++-1.18.19
  [✔] BiomesOPlenty-1.18.2-16.0.0.109-universal
  [✔] BuildersDelight-1.18.2-v.1.0
  [✔] bundledelight-1.18.2-1.2.0
  [✔] catalogue-1.6.2-1.18.2
  [✔] Chunk Pregenerator-1.18-4.3.0
  [✔] chunkloaders-1.2.7-forge-mc1.18
  [✔] cloth-config-6.5.102-forge
  [✔] Clumps-forge-1.18.2-8.0.0+17
  [✔] cofh_core-1.18.2-9.2.1.39
  [✔] collective-1.18.2-6.65
  [✔] combatroll-forge-1.1.5+1.18.2
  [✔] controllable-0.16.0-1.18.2
  [✔] Controlling-forge-1.18.2-9.0+23
  [✔] CopperOverhaul-MC1.18.2-v22.07.14re1
  [✔] corn_delight-1.0.6-1.18.2
  [✔] craftingtweaks-forge-1.18.2-14.0.7
  [✔] create_crystal_clear-0.2.1-1.18.2
  [✔] create_recycle_1.0.2_forge_1.18.2
  [✔] create-1.18.2-0.5.1.c
  [✔] createaddition-1.18.2-1.0.0
  [✔] CreateCasing-1.18.2-1.3-hotfix-1
  [✔] createdeco-1.3.3-1.18.2
  [✔] createoreexcavation-1.1.1
  [✔] createsifter-1.18.2-1.5.4.b-285
  [✔] CreativeCore_FORGE_v2.6.17_mc1.18.2
  [✔] curios-forge-1.18.2-5.0.9.1
  [✔] dynamiccrosshair-5.2+1.18.2-forge
  [✔] dynamiclightsreforged-1.18.2_v1.3.3
  [✔] DynamicTrees-1.18.2-1.0.4
  [✔] DynamicTreesBOP-1.18.2-3.0.1
  [✔] DynamicTreesPlus-1.18.2-1.0.4
  [✔] DynamicTreesQuark-1.18.2-2.2.4
  [✔] Effect_Overhaul-22.08.08-1.18.2
  [✔] EffectDescriptions-v3.0.1-1.18.2-Forge
  [✔] effortlessbuilding-1.18-2.40
  [✔] elevatorid-1.18.2-1.8.4
  [✔] ends_delight-1.18.2-1.2.1
  [✔] entityculling-forge-1.6.1-mc1.18.2
  [✘] excompressum-forge-1.18.2-5.0.3.jar (disabled)
  [✔] ExNihiloSequentia-1.18.2-20230528-221633
  [✔] ExNihiloTinkers-1.18.2-20230528-221633
  [✔] falling-attack-forge-1.18.2-2.0.0
  [✔] Fallingleaves-1.18.2-1.3.2
  [✔] FallingTree-1.18.2-3.5.5
  [✔] FarmersDelight-1.18.2-1.2.3
  [✔] FarmersRespite-1.18.2-1.3.0
  [✔] ferritecore-4.2.2-forge
  [✔] firstperson-forge-2.2.3-mc1.18.2
  [✔] fixedanvilrepaircost-1.18.2-3.1
  [✔] forgeautofish-4.2.0-1.18.2
  [✔] framework-forge-1.18.2-0.4.3
  [✔] fusion-1.0.5-forge-mc1.18
  [✔] geckolib-forge-1.18-3.0.57
  [✔] global_packs-forge-1.18.2-1.12.4_forge
  [✔] Iceberg-1.18.2-forge-1.0.49
  [✔] immersive_armors-1.5.6+1.18.2-forge
  [✔] inventoryessentials-forge-1.18.2-4.0.3
  [✔] inventorysorter-1.18-19.0.0
  [✔] inventorytotem-1.18.2-3.0
  [✔] ironchests-2.0.5-forge
  [✔] ironfurnaces-1.18.2-3.3.3
  [✔] ItemPhysic_v1.4.23_mc1.18.2
  [✔] jeed-1.18.2-1.11
  [✔] jei-1.18.2-9.7.2.1001
  [✔] JRFTL [1.18.1]-1.4.1
  [✔] JustEnoughProfessions-1.18.2-1.3.0
  [✔] JustEnoughResources-1.18.2-0.14.1.171
  [✔] kotlinforforge-3.12.0-all
  [✔] largemeals-1.18.2-2.0
  [✔] lazydfu-1.0-1.18+
  [✔] libIPN-forge-1.18.2-4.0.0
  [✔] LimitMobSpawn-18.4
  [✔] lodestone-1.18.2-1.4.2
  [✔] malum-1.18.2-1.5.0.1
  [✔] Mantle-1.18.2-1.9.45
  [✔] miners_delight-1.18.2-1.1.1
  [✔] mmlib-1.2.2-1.18.2
  [✔] modernfix-forge-5.7.1+mc1.18.2
  [✔] molten_geodes-1.18.2-0.3.1
  [✔] molten_vents-1.18.2-0.1.3
  [✔] moreminecarts-1.4.7
  [✔] MouseTweaks-forge-mc1.18-2.21
  [✔] mutil-1.18.2-4.5.0
  [✔] NaturesCompass-1.18.2-1.9.7-forge
  [✔] netherportalfix-forge-1.18.2-9.0.1
  [✔] NethersDelight-1.18.2-2.2.0
  [✔] notenoughanimations-forge-1.6.0-mc1.18.2
  [✔] oceansdelight-1.0.0-1.18.2
  [✔] oculus-flywheel-compat-1.18.2-0.2.1
  [✔] oculus-mc1.18.2-1.6.4
  [✔] player-animation-lib-forge-1.0.2+1.18
  [✔] PlayerRevive_FORGE_v2.0.13_mc1.18.2
  [✔] pollen-forge-1.6.1+1.18.2
  [✔] PresenceFootsteps-1.18.2-1.5.1-forge
  [✔] PuzzlesLib-v3.5.8-1.18.2-Forge
  [✔] Quark-3.2-358
  [✔] QuarkOddities-1.18
  [✔] radium-0.7.10
  [✔] rechiseled-1.1.2-forge-mc1.18
  [✔] rechiseledcreate-1.0.0-forge-mc1.18
  [✔] rubidium_extras-1.18.2_v1.3.2
  [✔] rubidium-0.5.6
  [✔] saturn-mc1.18.2-0.0.4
  [✔] Serene Seasons-1.18.2-7.0.0.13
  [✔] sereneseasonfix-1.18.2-1.0.6
  [✔] ShoulderSurfing-Forge-1.18.2-2.4.1
  [✔] shulkerboxtooltip-forge-3.1.3+1.18.2
  [✔] Simple Weapons 1.4.3 - 1.18.2
  [✔] SimpleStorageNetwork-1.18.2-1.7.0
  [✔] smoothboot(reloaded)-mc1.18.2-0.0.2
  [✔] smoothchunk-1.18.2-1.9
  [✔] soundphysics-forge-1.18.2-1.0.6
  [✔] speedyhoppers-1.18.2-1
  [✔] stackrefill-1.18.2-4.0
  [✔] starlight-1.0.2+forge.546ae87
  [✔] Steam_Rails-1.4.3+forge-mc1.18.2
  [✔] supermartijn642configlib-1.1.8-forge-mc1.18
  [✔] supermartijn642corelib-1.1.12-forge-mc1.18
  [✔] tconplanner-1.18.2-1.2.0
  [✔] TConstruct-1.18.2-3.6.4.113
  [✔] TerraBlender-forge-1.18.2-1.2.0.126
  [✔] tetra-1.18.2-4.10.1
  [✔] tetraenlarged-1.4-1.18.2
  [✔] tetranomicon-1.4-1.18.2
  [✔] tetrasdelight-1.18.2-1
  [✔] tetratic-combat 1.18.2-2.6.1
  [✔] TextruesRubidiumOptions-1.0.5-mc1.18.2
  [✔] tieredshulkerses-1.18.2-1.42
  [✔] tinkerleveling-0.4.0
  [✔] Tinkers Reforged 1.18.2-2.0.8
  [✔] Totem_Overhaul-22.08.08-1.18.2
  [✔] TravelersBackpack-1.18.2-7.1.38
  [✔] TravelersTitles-1.18.2-Forge-2.1.1
  [✔] Upcycle-1.18-(v.1.0.0)
  [✔] vanity-forge-1.0.1+1.18.2
  [✔] vestis-1.18.2-1.0.0
  [✔] villagespawnpoint-1.18.2-4.0
  [✔] voicechat-forge-1.18.2-2.4.21
  [✔] waymaker-1.18-1.1
  [✔] waystones-forge-1.18.2-10.2.1
  [✔] weaponleveling-1.18.2-1.4.3
  [✔] wthit-forge-4.13.6
  [✔] wthitharvestability-mc1.18.2-2.0.0
  [✔] Xaeros_Minimap_23.6.2_Forge_1.18.2
  [✔] XaerosWorldMap_1.33.0_Forge_1.18.2
  [✔] YungsApi-1.18.2-Forge-2.2.9
  [✔] YungsBetterDesertTemples-1.18.2-Forge-1.3.1
  [✔] YungsBetterDungeons-1.18.2-Forge-2.1.0
  [✔] YungsBetterMineshafts-1.18.2-Forge-2.2
  [✔] YungsBetterNetherFortresses-1.18.2-Forge-1.0.0
  [✔] YungsBetterOceanMonuments-1.18.2-Forge-1.0.3
  [✔] YungsBetterStrongholds-1.18.2-Forge-2.1.1
  [✔] YungsBetterWitchHuts-1.18.2-Forge-1.0.1
  [✔] YungsBridges-1.18.2-Forge-2.1.0
  [✔] YungsExtras-1.18.2-Forge-2.1.0
```

This is the error I get:

```
2023-08-21 20:07:45,263 main WARN Advanced terminal features are not available in this environment
20:07:45.451
game
[20:07:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, s3tupw1zard, --version, forge-40.2.10, --gameDir, C:\Users\s3tupw1zard\curseforge\minecraft\Instances\s3tupw1zard's Pack, --assetsDir, C:\Users\s3tupw1zard\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, a7882287ad6a4d4eb24607dbc4351b36, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ODA5ZDE1MmUtZWVmOS00MzcyLWI1N2QtNmVlYjJmNWZlYjg5, --xuid, 2535464763752313, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
20:07:45.455
game
[20:07:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
20:07:45.648
game
[20:07:45] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/s3tupw1zard/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
20:07:46.567
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.10\fmlcore-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.571
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.10\javafmllanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.574
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.10\lowcodelanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.577
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.10\mclanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.915
game
[20:07:46] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
20:07:47.925
game
Init ItemPhysic coremods ...
20:07:49.978
game
Exception in thread "main" java.lang.module.ResolutionException: Modules weaponleveling and MixinExtras.beta._9 export package com.llamalad7.mixinextras to module betterfortresses
20:07:49.979
game
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
20:07:49.979
game
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
20:07:49.979
game
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
20:07:49.979
game
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
20:07:49.979
game
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
20:07:49.979
game
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
20:07:49.979
game
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

The module that seems to fail to load is different each time.

Thank you

**Comment by xFirefalconx** [comment]
It seems that WeaponLeveling is using the mixins incorrectly, causing lots of crash issues. I've reported 2 crash bugs concerning the latest version just recently, too.

**Comment by GekidoLukas** [comment]
Same issue as #46. Will close in favor of #46 having more info.
