### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by muhammedesadcomert** [GekidoLukas/weaponleveling#62]
Minecraft: 1.20.4
Fabric Loader: 0.15.10
Mod version: 1.20.1-2.0.2

Crash logs: https://mclo.gs/iIghNyk

**Comment by nuypham** [comment]
Same issue.
Crash Minecraft version: 1.20.4
Fabric Loader: 0.15.9
Mod version: 1.20.1-2.0.2-fabric

[13:25:45] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.9
[13:25:45] [main/INFO]: Loading 60 mods:
	- architectury 11.1.17
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabricloader 0.15.9
	   \-- mixinextras 0.3.5
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- java 21
	- minecraft 1.20.4
	- weaponleveling 1.20.1-2.0.2
[13:25:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:25:46] [main/INFO]: Compatibility level set to JAVA_16
[13:25:46] [main/INFO]: Compatibility level set to JAVA_17
[13:25:46] [main/WARN]: Reference map 'ForgeConfigAPIPort-Common-refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message
[13:25:46] [main/WARN]: Error loading class: net/bettercombat/logic/WeaponRegistry (java.lang.ClassNotFoundException: net/bettercombat/logic/WeaponRegistry)
[13:25:47] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[13:25:52] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 123 milliseconds
[13:25:52] [main/ERROR]: Mixin apply for mod weaponleveling failed weaponleveling-common.mixins.json:MixinThrownTrident from mod weaponleveling -> net.minecraft.class_1685: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_7650 was not located in the target class net.minecraft.class_1685. Using refmap weaponleveling-common-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_7650 was not located in the target class net.minecraft.class_1685. Using refmap weaponleveling-common-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) ~[1.20.4-0.15.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
[13:25:52] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:185) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:174) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:874) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2609) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2580) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[1.20.4-0.15.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]

**Comment by GekidoLukas** [comment]
The Mod is not released for 1.20.4. Modrinth just showed up as such and I fixed that
